services:
  - type: web
    name: binance-topdown-dashboard
    env: python
    region: oregon
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.3
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATA_DIR
        value: /opt/render/project/src/data
      # Add API_KEY/API_SECRET and other sensitive keys in Render dashboard
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT dashboard:app
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
