name: CI & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyflakes

      - name: Lint (pyflakes)
        run: |
          python -m pyflakes .

      - name: Smoke import
        run: |
          python - << 'PY'
          import importlib.util, sys, os
          root = os.getcwd()
          files = [
              'dashboard.py',
              'topdown_daemon.py',
              'backtester.py',
              'utils.py',
          ]
          for f in files:
              p = os.path.join(root, f)
              if not os.path.exists(p):
                  continue
              spec = importlib.util.spec_from_file_location(f.replace('.py',''), p)
              mod = importlib.util.module_from_spec(spec)
              spec.loader.exec_module(mod)
              print('Imported', f, 'OK')
          PY

  deploy:
    needs: build-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        env:
          HOOK: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "$HOOK" ]; then
            echo "RENDER_DEPLOY_HOOK_URL secret is not set" && exit 1
          fi
          curl -fsS -X POST "$HOOK"
